import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const out=new URL('../docs/images/',import.meta.url);
await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||undefined});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5190/');
await page.locator('[data-testid="font-amiri"] [data-testid="font-preview"]').waitFor();
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:fileURLToPath(new URL('desktop.png',out)),fullPage:false});
await page.getByRole('button',{name:'فعّل الوضع الداكن'}).click();
await page.screenshot({path:fileURLToPath(new URL('dark.png',out)),fullPage:false});
await page.getByRole('button',{name:'فعّل الوضع الفاتح'}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:fileURLToPath(new URL('mobile.png',out)),fullPage:false});
const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
await page.setViewportSize({width:1440,height:1080});
await page.getByRole('button',{name:'الخطوط الإنجليزية',exact:true}).click();
await page.getByTestId('font-inter').getByTestId('font-preview').waitFor();
await page.screenshot({path:fileURLToPath(new URL('english.png',out)),fullPage:false});
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';});
await page.locator('.library-heading').evaluate(e=>e.scrollIntoView({block:'start'}));
await page.screenshot({path:fileURLToPath(new URL('english-mobile.png',out)),fullPage:false});
console.log(JSON.stringify({screenshots:'docs/images',pageErrors:errors,mobileOverflow,englishMobileOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)}));
await browser.close();
